apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: vidhya

spec:
  type: {{ .Values.service.type }}

  selector:
    app: vidhya

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{- if eq .Release.Namespace "production" }} 30008 {{- else if eq .Release.Namespace "staging" }} 30007 {{- end }}
      {{- end }}