name: reusable-workflow-for-docker build and push to GHCR
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  ci-pipeline-job:
    uses: vidhya101/reusable-workflows-vidhya101/.github/workflows/ci-pipeline.yml@main
    secrets: 
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}