name: reusable-workflow-for-docker build and push to GHCR # Workflow name visible in GitHub Actions UI

on:
  # Trigger workflow when code is pushed to main branch
  pull_request:
    branches:
    - main # Trigger workflow when PR is opened/updated targeting main
    paths-ignore: 
    - HELMCHART-VERSION

permissions:
  actions: read # Allows reading GitHub Actions metadata
  security-events: write # Required for CodeQL to upload results
  contents: write # Read access to repository content
  packages: write # Required to push Docker image to GHCR

env:
  OCI_REGISTRY: ghcr.io
  OCI_REPOSITORY: ${{github.repository_owner}}/helm-charts # This will be in the format owner/repo, e.g., vidhyashankergoel/reusable-workflows-vidhya101

jobs:

  ci-pipeline-job:  # ci-pipeline-job will run first when workflow is triggered
    uses: vidhyashankergoel/reusable-workflows-vidhya101/.github/workflows/ci-pipeline.yml@main  
    # Calling reusable workflow from another repository

    with:
      run_codeql: true         # Enable CodeQL security scan
      run_sonarqube: true      # Enable SonarQube analysis
      run_build: true          # Enable Docker build step
      run_ghcr_publish: true   # Enable pushing image to GHCR

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}   # DockerHub login username
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   # DockerHub password/token
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}           # SonarQube authentication token

  deploy-with-kubectl: # deploy-with-kubectl job will run after ci-pipeline-job completes successfully
    needs: ci-pipeline-job   # This job will run after ci-pipeline-job completes successfully
    uses: vidhyashankergoel/reusable-workflows-vidhya101/.github/workflows/deploy-with-kubectl.yml@main  
    # Calling another reusable workflow for deployment

    with:
      ENVIRONMENT: STAGING
      IMAGE_NAME: ghcr.io/vidhyashankergoel/vidhya_app

    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}  # Kubernetes config file content as a secret

  selenium-test: # selenium-test job will run after deploy-with-kubectl job completes successfully
    needs: deploy-with-kubectl 
    uses: vidhyashankergoel/reusable-workflows-vidhya101/.github/workflows/Selenium-test.yml@main
    with:
      ENVIRONMENT: STAGING  # Pass the environment variable to the Selenium test workflow
                            # Changed the base URL http://192.168.56.10:30082 to staging as the Selenium test workflow will use the ENVIRONMENT variable to determine the base URL for testing

  publish-helm-charts:
    needs: selenium-test # This job will run after selenium-test job completes successfully
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v5

    - name: Publish Helm Chart to OCI registry
      uses: vidhyashankergoel/helm-actions@v1.0               #changing release version for fix
      with:
        oci_registry: ${{ env.OCI_REGISTRY }}
        oci_repository: ${{ env.OCI_REPOSITORY }}
        auth_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication to GHCR