
name: reusable-workflow-for-docker build and push to GHCR # This workflow is designed to be reusable and can be called from other workflows in different repositories. It performs a CI pipeline that includes running CodeQL analysis, SonarQube analysis, building a Docker image, and publishing it to GitHub Container Registry (GHCR). The workflow is triggered on push and pull request events to the main branch.
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  actions: read
  security-events: write
  contents: read
  packages: write

jobs:

  ci-pipeline-job:
    uses: vidhyashankergoel/reusable-workflows-vidhya101/.github/workflows/ci-pipeline.yml@main
    with:
      run_codeql: true
      run_sonarqube: true
      run_build: true
      run_ghcr_publish: true
    secrets:

      # DockerHub username used for docker login
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      # DockerHub password or access token
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # SonarQube authentication token used for
      # sending code analysis results to SonarCloud
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-with-kubectl:
    needs: ci-pipeline-job
    runs-on: github-action-scaleset-demo # This job is responsible for deploying the application to a Kubernetes cluster using kubectl. It runs after the CI pipeline job is completed successfully. The job checks out the code, sets up kubectl, and applies the Kubernetes manifests to deploy the application.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install kubectl 
        run: |
          curl -LO "http://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/
          kubectl version --client  

      - name: configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG}}" > ~/.kube/config
          kubectl version 
          kubectl get nodes

      - name: Install yg
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version 

      - name: update image name in deployment YAML
        run: |
          IMAGE_TAGS="${{github.run_id}}-${GITHUB_SHA::7}"
          IMAGE="ghcr.io/vidhyashankergoel/vidhya_app:${IMAGE_TAGS}"
          yq e -i '.spec.template.spec.containers[0].image = strenv(IMAGE)' ./manifests/deployment.yml
          cat ./manifests/deployment.yml