name: self hosted runner 
on:
  push:
    branches:
      - dev

jobs:
  demo-1:
    name: demo-job-1
    runs-on: ubuntu-latest #picked github hosted runner with label "ubuntu-latest"
    steps:
      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat/etc/os-release
          echo "Runner Name: ${{runner.name}}"
          echo "Runner OS: ${{runner.os}}"


  demo-2:
    name: demo-job-2
    runs-on: self-hosted #pickup self hosted runner with the label 'self hosted'
    steps:
      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat/etc/os-release
          echo "Runner Name: ${{runner.name}}"
          echo "Runner OS: ${{runner.os}}"