name: self hosted runner 
on:
  push:
    branches:
      - dev

jobs:
  demo-1:
    name: demo-job-1
    runs-on: ubuntu-latest #picked github hosted runner with label "ubuntu-latest"
    steps:
      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat/etc/os-release
          echo "Runner Name: ${{runner.name}}"
          echo "Runner OS: ${{runner.os}}"
          sleep 30s

  demo-4:
    name: demo-job-4
    runs-on: [self-hosted , vidhya101] #self hosted inside a linux VM 
    steps:
      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat/etc/os-release
          echo "Runner Name: ${{runner.name}}"
          echo "Runner OS: ${{runner.os}}"
          sleep 90s

  demo-2:
    name: demo-job-2
    runs-on: github-action-scaleset-demo #pickup by arc and runs inside kubernetes as a pod 
    steps:
      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat/etc/os-release
          echo "Runner Name: ${{runner.name}}"
          echo "Runner OS: ${{runner.os}}"
          sleep 90s
  
  demo-3:
    name: demo-job-3
    runs-on: github-action-scaleset-demo #pickup by arc and runs inside kubernetes as a pod 
    steps:
      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat/etc/os-release
          echo "Runner Name: ${{runner.name}}"
          echo "Runner OS: ${{runner.os}}"
          sleep 90s